version: '3.4'

name: optidfs-backend-debug
services:
  optidfs-backend-debug:
    container_name: backend
    image: optidfs-backend
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678
